#!/bin/bash

####################################################
#   Retrieve arguments / set global variables      #
####################################################

app=letsencrypt

domain=$1
admin=$2

####################################################
#   Check that admin user is an existing account   #
####################################################

sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
if [[ ! $? -eq 0 ]]; then
    echo "Error : the chosen admin user does not exist"
    exit 1
fi

sudo yunohost app setting $app admin -v $admin
sudo yunohost app setting $app domain -v $domain

####################################################
#   Nginx and SSOwat configuration                 #
####################################################

## Let's encrypt check the domain/server by adding files that can be
## accessed at domain.tld/.well-known/acme-challenge, which the Lets 
## encrypt CA server tries to access

# Nginx location block
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# SSOwat unprotected regex
sudo yunohost app setting $app unprotected_regex \
  -v "$domain/%.well%-known/acme%-challenge/.*$"

# Restart services
sudo service nginx restart
sudo yunohost app ssowatconf

####################################################
#   Install letsencrypt                            #
####################################################

installdir=/root/.letsencrypt/
webrootdir=/tmp/letsencrypt-auto
logfile=letsEncrypt.log

# Clone the git repo, call letencrypt to init stuff
sudo yunohost app setting $app installdir -v $installdir
sudo git clone https://github.com/letsencrypt/letsencrypt $installdir
sudo $installdir/letsencrypt-auto

if [ ! -d /etc/letsencrypt ]; then
    cat << EOF
	Directory /etc/letsencrypt was not found. Something went
    wrong during the install/initialization of letsencrypt ?
EOF
    exit 2
fi

# Move the letsencrypt config file to /etc/letsencrypt
sed -i "s|ADMIN_EMAIL|$admin@$domain|g" ../conf/letsencrypt.conf
sed -i "s|WEBROOT_PATH|$webrootdir|g"   ../conf/letsencrypt.conf
sudo cp ../conf/letsencrypt.conf /etc/letsencrypt/conf.ini

# Create the rootdir directory
sudo mkdir -p $webrootdir

# Actually try to get the certificates
sudo $installdir/letsencrypt-auto                            \
    certonly                                                 \
    --config  /etc/letsencrypt/conf.ini                      \
    --domains $domain                                        \
    2>&1 | tee $logfile

sudo cp $logfile /root/$logfile

# Check it worked
congrat=`sudo cat $logfile | grep Congratulations!`
if [[ $congrat == "" ]]; then
    cat << EOF
	There was a problem after the call to letsencrypt-auto.
	This shouldn't break your current certificates install,
	but you'll probably need to investigate what happened  
	using /root/$logfile and nginx logs before reattempting
	to install letsencrypt.                                
EOF
    exit 2
fi

####################################################
#   Cron job for automatic renewal                 #
####################################################

sed -i "s|ADMIN_EMAIL|$admin@$domain|g" ../sources/certificateRenewer.sh
chmod +x ../sources/certificateRenewer.sh
sudo cp  ../sources/certificateRenewer.sh /etc/cron.weekly/

####################################################
#   Link certificates                              #
####################################################

# Add metronome permissions to the letsencrypt certs
sudo chown -R   root:metronome /etc/letsencrypt/archive/
sudo chown -R   root:metronome /etc/letsencrypt/live/
sudo chmod g+rx /etc/letsencrypt/archive/
sudo chmod g+rx /etc/letsencrypt/live/

# Backup certs
certPath=/etc/yunohost/certs/
sudo mv $certPath/$domain $certPath/$domain.beforeLetsEncrypt

# Link letsencrypt certs in the yunohost cert folder
sudo mkdir $certPath/$domain
LE_LIVE_FOLDER=/etc/letsencrypt/live
sudo ln -s $LE_LIVE_FOLDER/$domain/fullchain.pem $certPath/$domain/crt.pem
sudo ln -s $LE_LIVE_FOLDER/$domain/privkey.pem   $certPath/$domain/key.pem

# ################################################# #
#  Restart services                                 #
# ################################################# #

sudo service nginx restart
sudo service metronome restart



