#!/bin/bash

#
#
#   Warning ! Not tested !
#
#

app=letsencrypt
domain=$(sudo yunohost app setting $app domain)

backupFolder=/root/.letsencrypt-backupDuringUninstall
sudo mkdir $backupFolder

# Remove letsencrypt git repo clone
sudo rm -rf /root/.letsencrypt

####################################################
#   Backup conf                                    #
####################################################

# Backup nginx conf file
sudo mv /etc/nginx/conf.d/$domain.d/$app.conf $backupFolder
# Backup /etc/letsencrypt
sudo mv /etc/letsencrypt $backupFolder/etc_letsencrypt

####################################################
#   Link backuped certificates                     #
####################################################

certPath=/etc/yunohost/certs/
# Backup letsencrypt certs
sudo mv $certPath/$domain $backupFolder
# Link certs that were used before install
sudo mv $certPath/$domain.beforeLetsEncrypt $certPath/$domain

# ################################################# #
#  Restart services                                 #
# ################################################# #

sudo service nginx restart
sudo service metronome restart

