#!/bin/bash

#
#
#   Warning ! Not tested !
#
#

app=letsencrypt
domains=$(sudo yunohost app setting $app installDomains)

backupFolder=/root/.letsencrypt-backupDuringUninstall
sudo mkdir $backupFolder

# Remove letsencrypt git repo clone
sudo rm -rf /root/.letsencrypt

# Remove cron job
sudo rm /etc/cron.weekly/certificateRenewer

# Backup /etc/letsencrypt
sudo mv /etc/letsencrypt $backupFolder/etc_letsencrypt

####################################################
#   Restore backuped certificates                  #
####################################################

certPath=/etc/yunohost/certs/

for domain in $domains
do
    # Backup nginx conf file
    sudo mv /etc/nginx/conf.d/$domain.d/000-$app.conf $backupFolder/$domain.nginx

    # If a backup of self-signed cert exist
    if [ -d "$certPath/$domain.beforeLetsEncrypt" ]; then
        # Backup letsencrypt certs
        sudo mv $certPath/$domain $backupFolder
        # Link certs that were used before install
        sudo mv $certPath/$domain.beforeLetsEncrypt $certPath/$domain
    fi
done

# ################################################# #
#  Restart services                                 #
# ################################################# #

sudo service nginx restart
sudo service metronome restart

