#!/bin/bash


#
#
#   Warning ! Not tested !
#
#

app=letsencrypt
domain=$(sudo yunohost app setting $app domain)

# Remove configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

####################################################
#   Link backuped certificates                     #
####################################################

# Backup letsencrypt certs
certPath=/etc/yunohost/certs/
sudo mv $certPath/$domain $certPath/$domain.letsEncrypt
sudo mv $certPath/$domain.beforeLetsEncrypt $certPath/$domain

# ################################################# #
#  Restart services                                 #
# ################################################# #

sudo service nginx restart
sudo service metronome restart

