#!/bin/bash

app=letsencrypt
domains=$(sudo yunohost app setting $app installDomains)

# Add 000- as prefix to nginx conf
for domain in $domains
do
    # If using old nginx conf path (without prefix), migrate it
    if [ -e  "/etc/nginx/conf.d/$domain.d/$app.conf" ]; then
      sudo mv /etc/nginx/conf.d/$domain.d/$app.conf \
              /etc/nginx/conf.d/$domain.d/000-$app.conf
    fi
done

# Move letsencrypt client to /opt/yunohost/letsencrypt
if sudo test -f "/root/.letsencrypt/letsencrypt-auto";
then
    sudo mkdir -p /opt/yunohost/
    sudo mv /root/.letsencrypt/ /opt/yunohost/letsencrypt/
    sudo sed -i "s|\/root\/\.letsencrypt/|/opt/yunohost/letsencrypt/|g" /etc/cron.weekly/certificateRenewer
    sudo yunohost app setting $app installdir -v /opt/yunohost/letsencrypt/
fi

# Update certificateRenewer
admin=$(sudo yunohost app setting $app admin)
mainDomain=$(sudo cat /etc/yunohost/current_host)

sed -i "s|ADMIN_EMAIL|$admin@$mainDomain|g" ../sources/certificateRenewer
sed -i "s|DOMAIN_NAME|$mainDomain|g"        ../sources/certificateRenewer
chmod +x ../sources/certificateRenewer
sudo cp  ../sources/certificateRenewer /etc/cron.weekly/

sudo service nginx reload
